/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import DAO.UsuarioDAOImp;
import Entidades.Usuario;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

/**
 *
 * @author juanc
 */
public class MostrarUsuario extends javax.swing.JFrame {

    static UsuarioDAOImp usuarioImp;
    static Usuario usuario;

    /**
     * Creates new form MostrarUsuario
     */
    public MostrarUsuario(UsuarioDAOImp usuarioImp, Usuario usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.usuarioImp = usuarioImp;
        this.usuario = usuario;
        bGuardar.setVisible(false);
        llenarInfo();
    }

    public void llenarInfo() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        List<String> generosM = usuario.getGustosMusicales();
        List<String> generosP = usuario.getGustosPeliculas();

        areaName.setText(usuario.getName());
        areaName.setEditable(false);
        areaUsername.setText(usuario.getUsername());
        areaUsername.setEditable(false);
        areaPassword.setText(usuario.getPassword());
        areaPassword.setEditable(false);
        areaEdad.setText(Integer.toString(usuario.getEdad()));
        areaEdad.setEditable(false);
        areaSexo.setText(usuario.getSexo());
        areaSexo.setEditable(false);
        areaFechaNacimiento.setText(sdf.format(usuario.getFechaNacimiento()));
        areaFechaNacimiento.setEditable(false);
        for (int i = 0; i < generosM.size(); i++) {
            areaGM.append(generosM.get(i) + ",");
        }
        for (int i = 0; i < generosP.size(); i++) {
            areaGP.append(generosP.get(i) + ",");
        }
        areaGM.setEditable(false);
        areaGP.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        areaName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        areaUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        areaFechaNacimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        areaEdad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        areaPassword = new javax.swing.JTextField();
        areaSexo = new javax.swing.JTextField();
        bEliminar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaGP = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaGM = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 550));
        setSize(new java.awt.Dimension(850, 550));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 10, 220, 70);

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 80, 50, 16);
        getContentPane().add(areaName);
        areaName.setBounds(180, 80, 590, 30);

        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 120, 60, 16);
        getContentPane().add(areaUsername);
        areaUsername.setBounds(180, 120, 590, 30);

        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 160, 60, 16);
        getContentPane().add(areaFechaNacimiento);
        areaFechaNacimiento.setBounds(180, 280, 590, 30);

        jLabel6.setText("Edad");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 200, 60, 16);
        getContentPane().add(areaEdad);
        areaEdad.setBounds(180, 200, 70, 30);

        jLabel7.setText("Sexo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 240, 60, 16);

        jLabel11.setText("Fecha Nacimiento");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 280, 110, 16);

        jLabel12.setText("Géneros Musicales");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 320, 110, 16);

        jLabel2.setText("Géneros de Película");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 360, 120, 16);
        getContentPane().add(areaPassword);
        areaPassword.setBounds(180, 160, 590, 30);
        getContentPane().add(areaSexo);
        areaSexo.setBounds(180, 240, 590, 30);

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(bEliminar);
        bEliminar.setBounds(660, 460, 100, 25);

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });
        getContentPane().add(bEditar);
        bEditar.setBounds(80, 460, 100, 25);

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(bGuardar);
        bGuardar.setBounds(190, 460, 100, 25);

        areaGP.setColumns(20);
        areaGP.setRows(5);
        jScrollPane1.setViewportView(areaGP);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 360, 590, 30);

        areaGM.setColumns(20);
        areaGM.setRows(5);
        jScrollPane2.setViewportView(areaGM);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(180, 320, 590, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        usuarioImp.delete(usuario);
        this.dispose();
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed

        areaName.setEditable(true);
        areaUsername.setEditable(false);
        areaPassword.setEditable(true);
        areaEdad.setEditable(false);
        areaSexo.setEditable(false);
        areaFechaNacimiento.setEditable(false);
        areaGM.setEditable(true);
        areaGP.setEditable(true);
        
        bGuardar.setVisible(true);
    }//GEN-LAST:event_bEditarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        String name = areaName.getText();
        String username = usuario.getUsername();
        String password = areaPassword.getText();
        int edad = usuario.getEdad();
        String sexo = usuario.getSexo();
        Date fechaNacimiento = usuario.getFechaNacimiento();

        List<String> generosMusica = new ArrayList<>();
        List<String> generosPelicula = new ArrayList<>();
        String[] gm = areaGM.getText().split(",");
        String[] gp = areaGP.getText().split(",");

        generosMusica.addAll(Arrays.asList(gm));
        generosPelicula.addAll(Arrays.asList(gp));
        
        Usuario usuario = new Usuario(username, password, name, edad, sexo, fechaNacimiento, generosMusica, generosPelicula);
        
        usuarioImp.update(usuario);
        this.dispose();
    }//GEN-LAST:event_bGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarUsuario(usuarioImp, usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaEdad;
    private javax.swing.JTextField areaFechaNacimiento;
    private javax.swing.JTextArea areaGM;
    private javax.swing.JTextArea areaGP;
    private javax.swing.JTextField areaName;
    private javax.swing.JTextField areaPassword;
    private javax.swing.JTextField areaSexo;
    private javax.swing.JTextField areaUsername;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
